# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :beta do
  	build_app(export_method: "development",clean: true)
  	pgyer(api_key: "dcf655a616d2d0e0e1a2e15ab8095c8a", user_key: "6b1a701cea8f86180d1eb8699a0c1211",update_description: "update by fastlane")
  end
end
